#!/bin/bash




































































































































































































































































































































A='\e[1;34m'
r='\e[1;31m'
v='\e[1;32m'
f='\e[1;35m'
b='\e[1;37m'
ac='\e[1;36m'
if [ ! -e /data/data/com.termux/files/usr/bin/cowsay ]; then
sleep 0.4
echo
echo -e "$A[$r*$A]${r}Error Falta Cowsay${b}"
echo
echo -e "$v pkg install cowsay$b"
echo
exit
fi
if [ ! -e /data/data/com.termux/files/usr/bin/python2 ]; then
sleep 0.4
echo
echo -e "$A[$r*$A]${r}Error Falta Python2${b}"
echo
echo -e "$v pkg install python2 -y $b"
echo
exit
fi
trap adios INT
adios() {
sleep 0.1
echo
echo -e "
        $A[$v+$A]$ac Finalizado
        $A[$v+$A]$ac Gracias Por Utilizar Mi  Script
        $A[$v+$A]$ac By: Anonymous Zpt$b


"
sleep 0.3
exit
}
b() {
sleep 0.5
echo -e "$A
▄▄▄▄▄▄
 ██▀▀▀▀██
 ██    ██   ▄█████▄  ██▄████▄  ██▄████▄   ▄████▄    ██▄████
 ███████    ▀ ▄▄▄██  ██▀   ██  ██▀   ██  ██▄▄▄▄██   ██▀
 ██    ██  ▄██▀▀▀██  ██    ██  ██    ██  ██▀▀▀▀▀▀   ██
 ██▄▄▄▄██  ██▄▄▄███  ██    ██  ██    ██  ▀██▄▄▄▄█   ██
 ▀▀▀▀▀▀▀    ▀▀▀▀ ▀▀  ▀▀    ▀▀  ▀▀    ▀▀    ▀▀▀▀▀    ▀▀
$b"
}
banner() {
clear
b
echo "¿Que Deseas Realizar?"
echo -e "
	$A[${r}01$A]$v Iniciar Personalizacion

	$A[${r}02$A]$v Eliminar Personalizacion

	$A[${r}03$A]$v Salir
"
inicio
}
inicio() {
printf  "$v¦-->$b "
read opcion
case $opcion in
01|1)
clear
echo -e "Iniciando Banner Personalizado"
sleep 2
rm $PREFIX/etc/motd &>> /dev/null
rm $PREFIX/etc/bash.bashrc &>> /dev/null
touch $PREFIX/etc/bash.bashrc
echo "if [ -x /data/data/com.termux/files/usr/libexec/termux/command-not-found ]; then" >> $PREFIX/etc/bash.bashrc
echo "	command_not_found_handle() {" >> $PREFIX/etc/bash.bashrc
echo '		/data/data/com.termux/files/usr/libexec/termux/command-not-found "$1"' >> $PREFIX/etc/bash.bashrc
echo "	}" >> $PREFIX/etc/bash.bashrc
echo "fi" >> $PREFIX/etc/bash.bashrc
echo "#" >> $PREFIX/etc/bash.bashrc
echo "python2 ~/T-banner2/NET/.Banner" >> $PREFIX/etc/bash.bashrc
echo "#By Anonymous Zpt" >> $PREFIX/etc/bash.bashrc
echo "PS1='\$ '" >> $PREFIX/etc/bash.bashrc
clear
sleep 0.5
echo -e "$v"
echo "Finalizado"|cowsay -d
echo -e "$b"
sleep 2
banner
inicio
;;
02|2)
echo -e "Comenzando Banner Defaul"
sleep 2
rm $PREFIX/etc/motd &>> /dev/null
rm $PREFIX/etc/bash.bashrc &>> /dev/null
cp ~/T-banner2/NET/motd $PREFIX/etc
cp ~/T-banner2/NET/bash.bashrc $PREFIX/etc
sleep 0.5
echo -e "$v"
echo "Finalizado"|cowsay -db
echo -e "$b"
sleep 2
banner
inicio
;;
03|3)
adios
;;
Clear|clear)
banner
inicio
;;
*)
echo -e "$A[$b*$A]$b Comando Invalido"
inicio
;;
esac
}
banner
inicio
